routes/web.php
<?php
//Route::get('/id_manager','NepalController@id_manager');

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * For Admin Panel
 *
 * */

//Auth::routes();
//Route::get('/welcome', function (){
//    return view('welcome');
//});

//Route::get('lgisadminpanel/login', 'AdminController@login');
Route::get( 'lgisadminpanel/login', ['middleware' => 'guest', 'uses' => 'AdminController@login'] );

Route::post('lgisadminpanel/login', 'AdminController@postLogin');
//Route::post('lgisadminpanel/login/', ['as' => 'lgisadminpanel.login', 'uses' => 'AdminController@postLogin']);

Route::group(['middleware' => 'auth'], function()
{
    Route::get('lgisadminpanel',          				['uses' => 'AdminController@index']				    );
    Route::get('lgisadminpanel/suggestion/{id}','AdminController@detail');
    Route::get('lgisadminpanel/suggestion/delete/{id}','AdminController@delete');

    Route::resource('lgisadminpanel/province', 'AdminProvinceController');
    Route::get('lgisadminpanel/province/get_from_web/{id}','AdminProvinceController@get_data_from_web');

    Route::resource('lgisadminpanel/district', 'AdminDistrictController');
    Route::get('lgisadminpanel/district/get_from_web/{id}','AdminDistrictController@get_data_from_web');

    Route::resource('lgisadminpanel/body', 'AdminBodyController');
    Route::get('lgisadminpanel/body/get_from_web/{id}','AdminBodyController@get_data_from_web');
    Route::get('lgisadminpanel/body/otherinformation/{id}','AdminBodyController@getOtherInformationForm');
    Route::post('lgisadminpanel/body/otherinformation/{id}','AdminBodyController@postOtherInformationForm');


    Route::get('lgisadminpanel/ward/create/{id}', 'AdminWardController@create');
    Route::resource('lgisadminpanel/ward', 'AdminWardController');

});

Route::get('lgisadminpanel/logout', 'AdminController@getLogout');

/*
 * For Web Application
 *
 * */

Route::get('/',function (){
    $locale = Session::get ('locale');
    if(empty($locale)){
        Session::put('locale','en');
        $locale = 'en';
    }
    return redirect('/' . $locale);
});

Route::get('{locale}/contact', function ($locale){
    \App::setLocale($locale);
    return view('app.site.contact');
});

Route::get('{locale}/about', function ($locale){
    \App::setLocale($locale);
    return view('app.site.about');
});

Route::get('{locale}/help', function ($locale){
    \App::setLocale($locale);
    return view('app.site.help');
});

Route::get('/{locale}', 'NepalController@index');
Route::get('/{locale}/body/metro', 'NepalController@getMetro');
Route::get('/{locale}/body/submetro', 'NepalController@getSubMetro');
Route::get('/{locale}/body/munic', 'NepalController@getMunic');
Route::get('/{locale}/body/ruralmunic', 'NepalController@getRuralMuni');

//Route::get('/{locale}/search', 'NepalController@livesearch');

Route::post('/nepal/', ['as' => 'suggestion_store', 'uses' => 'NepalController@store']);

Route::get('{locale}/province','ProvinceController@index');
Route::get('/{locale}/province/{id}','ProvinceController@show');


Route::get('/{locale}/district', 'DistrictController@index');
Route::get('/{locale}/district/{id}', 'DistrictController@show');


Route::get('/{locale}/body', 'BodyController@index');
Route::get('/{locale}/body/{id}', 'BodyController@show');

app/Http/Controllers/BodyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\LocalBody;
use Illuminate\Support\Facades\DB;


class BodyController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @param $locale
     * @return \Illuminate\Http\Response
     */
    public function index($locale)
    {

        \App::setLocale($locale);

        $body = LocalBody::all();

        if ( \Request::is('api/*')) {

            //for api fetch all
            $bodies = LocalBody::all();

            $body = array();
            foreach ($bodies as $b) {
                array_push($body, array(
                        'district_id' => $b->district_id,
                        'province_id' => $b->province_id,
                        'body_name' => $b->translation()->first()->name,
                        'body_description' => $b->translation()->first()->description,
                        'type' => $b->type,
                        'ward' => $b->ward_no
                    )
                );
            }
            return response()->json($body);
        }

        $body = $body->sort(function($a, $b)
        {
            $a = $a->translation()->first()->name;
            $b = $b->translation()->first()->name;
            //here you can do more complex comparisons
            //when dealing with sub-objects and child models
            if ($a === $b) {
                return 0;
            }
            return ($a > $b) ? 1 : -1;
        });

        $body = $this::paginate($body, 5);

        return view('app.body.index')->with('bodies', $body);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($locale,$id)
    {
        \App::setLocale($locale);
        $body = LocalBody::findOrFail($id);

        if ( \Request::is('api/*')) {

            $body_detail = array();

            array_push($body_detail, array(
                    'district_id' => $body->district_id,
                    'province_id' => $body->province_id,
                    'body_name' => $body->translation()->first()->name,
                    'body_description' => $body->translation()->first()->description,
                    'type' => $body->type,
                    'ward' => $body->ward_no,
                )
            );
            return response()->json($body_detail);
        }

        return view('app.body.details')->with('body',$body);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    function paginate($items, $perPage)
    {
        $pageStart = request('page', 1);
        $offSet    = ($pageStart * $perPage) - $perPage;
        $itemsForCurrentPage = $items->slice($offSet, $perPage);

        return new \Illuminate\Pagination\LengthAwarePaginator(
            $itemsForCurrentPage, $items->count(), $perPage,
            \Illuminate\Pagination\Paginator::resolveCurrentPage(),
            ['path' => \Illuminate\Pagination\Paginator::resolveCurrentPath()]
        );
    }

    public function areaOfWards($id){

        if ( \Request::is('api/*')) {

            $body = LocalBody::findOrFail($id);
            $wards = $body->ward;

            $data = array();

            foreach ($wards as $ward) {
                array_push($data, array(
                    'name' => $ward->name,
                    'area' => $ward->area
                ));
            }

            return response()->json($data);
        }
    }

    public function populationOfWards($id){
        if ( \Request::is('api/*')) {
            $body = LocalBody::findOrFail($id);
            $wards = $body->ward;

            $data = array();

            foreach ($wards as $ward) {
                array_push($data, array(
                    'name' => $ward->name,
                    'population' => $ward->population
                ));
            }
            return response()->json($data);
        }
    }

    public function populationOfMaleAndFemale($id){
        if ( \Request::is('api/*')) {
            $body = LocalBody::findOrFail($id);

            $data = array();
            array_push($data,[
                'name' => 'Male Population',
                'population' => (double) $body->translation('en')->first()->male_population
            ]);

            array_push($data,[
                'name' => 'Female Population',
                'population' => (double) $body->translation('en')->first()->female_population
            ]);

            return response()->json($data);
        }
    }

    public function populationOfBodyAndDistrict($id){
        if ( \Request::is('api/*')) {
            $body = LocalBody::findOrFail($id);

            $data = array();
            array_push($data,[
                'name' => 'Population of District',
                'population' => (double) $body->district->translation('en')->first()->population
            ]);

            array_push($data,[
                'name' => 'Population of Body',
                'population' => (double) $body->translation('en')->first()->population
            ]);

            return response()->json($data);
        }
    }

    public function areaOfBodyAndDistrict($id){
        if ( \Request::is('api/*')) {
            $body = LocalBody::findOrFail($id);

            $data = array();
            array_push($data,[
                'name' => 'Area of District',
                'area' => (double) $body->district->translation('en')->first()->area
            ]);

            array_push($data,[
                'name' => 'Area of Body',
                'area' => (double) $body->translation('en')->first()->area
            ]);

            return response()->json($data);
        }
    }

    public function otherBodyInformation($id){
        $information = DB::table('other_information')->where('local_body_id',$id)->first();

        $data = array();

        array_push($data,[
            'name' => 'Hospital',
            'number' => $information->hospital
        ]);

        array_push($data,[
            'name' => 'Health Centre',
            'number' => $information-> health_centre
        ]);

        array_push($data,[
            'name' => 'Health Post',
                'number' => $information->health_post
        ]);

        array_push($data,[
            'name' => 'Sub Health Post',
                'number' => $information->sub_health_post
        ]);


        array_push($data,[
            'name' => 'Ayurvedic Medicine Centre',
                'number' => $information->ayurvedic_medicine_centre,
        ]);

        array_push($data,[
            'name' => 'rural_health_social_volunteer',
                'number' => $information->rural_health_social_volunteer
        ]);

        array_push($data,[
            'name' => "child_care_centre",
                'number' => $information->child_care_centre
        ]);

        array_push($data,[
            'name' => 'primary_school',
                'number' => $information->primary_school
        ]);

        array_push($data,[
            'name' => 'secondary_school',
                'number' => $information->secondary_school
        ]);

        array_push($data,[
            'name' => 'College',
                'number' => $information->college
        ]);

        array_push($data,[
            'name' => "university",
                'number' => $information->university
        ]);

        //
        array_push($data,[
            'name' => 'banijya_bank',
                'number' => $information->banijya_bank
        ]);

        array_push($data,[
            'name' => 'development_bank',
                'number' => $information->development_bank
        ]);

        array_push($data,[
            'name' => 'financial_institution',
                'number' => $information->financial_institution
        ]);

        array_push($data,[
            'name' => 'laghu_bittiya_sanstha_ltd',
                'number' => $information->laghu_bittiya_sanstha_ltd
        ]);

        array_push($data,[
            'name' => 'saving_and_credit_cooperative_ltd',
                'number' => $information->saving_and_credit_cooperative_ltd
        ]);

        array_push($data,[
            'name' => 'pitch_road',
                'number' => $information->pitch_road
        ]);

        array_push($data,[
            'name' => 'semi_pitch_road',
                'number' => $information->semi_pitch_road
        ]);

        array_push($data,[
            'name' => 'rough_road',
                'number' => $information->rough_road
        ]);

        return response()->json($data);

    }

    function otherBodyInformation2($id){

        $information = DB::table('other_information')->where('local_body_id',$id)->first();

        $data = array();

        array_push($data,[
            'name' => 'driking_water_available',
                'number' => $information->driking_water_available
        ]);

resources/views/admin/pages/body/create.blade.php
@extends('admin.master')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Bodies - Create
                <small>Control Panel</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ url('/admin') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li><a href="{{ url('/admin/body') }}"><i class="fa fa-dashboard"></i> Province</a></li>
                <li class="active"><i class="fa fa-dashboard"></i> create</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Your Page Content Here -->

            <div class="row">
                <div class="col-md-6">
                    <p class="text-center">In English</p>
                </div>

                <div class="col-md-6">
                    <p class="text-center">In Nepali</p>
                </div>
            </div>
            {!! Form::open(array('route' => 'body.store','method'=>'POST', 'enctype' => 'multipart/form-data' )) !!}
            @include('admin.partials._form_body_create')
            {!! Form::close() !!}
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection

resources/views/admin/pages/body/edit.blade.php
@extends('admin.master')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Bodies - Edit
                <small>Control Panel</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ url('/admin') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li><a href="{{ url('/admin/body') }}"><i class="fa fa-dashboard"></i> Bodies</a></li>
                <li class="active"><i class="fa fa-dashboard"></i> edit</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Your Page Content Here -->

            @if(Session::has('message'))
                <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
            @endif

            <div class="row">
                <div class="col-md-6">
                    <p class="text-center">In English</p>
                </div>

                <div class="col-md-6">
                    <p class="text-center">In Nepali</p>
                </div>
            </div>

            {!! Form::model($body, ['method' => 'PATCH','enctype' => 'multipart/form-data' ,'route' => ['body.update', $body->id]]) !!}
            @include('admin.partials._form_body_edit')
            {!! Form::close() !!}
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection

resources/views/admin/pages/body/index.blade.php
@extends('admin.master')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Bodies
                <small>Admin-Panel</small>
                <span>
                    <a href="{{ route('body.create')}}"  style="padding-left: 15px;"><i class="fa fa-plus"></i></a>
                </span>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ url('/admin') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li class="active">Bodies</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Your Page Content Here -->
            @php
                $count = 1;
                $break = 2;
            @endphp

            @foreach($bodies as $body)
                @if( $count == 1)
                    <div class="row">
                        @endif

                        <div class="col-md-6">
                            <div class="box box-solid">
                                <div class="box-header with-border">
                                    <i class="fa fa-text-width"></i>
                                    <h3 class="box-title">{{ $body->translation('en')->first()->name }}</h3>
                                </div>
                                <!-- /.box-header -->
                                <div class="box-body">
                                    <dl class="dl-horizontal">
                                        <dt>Description</dt>
                                        <dd>{{ $body->translation('en')->first()->description }}</dd>
                                        <dt>Created On:</dt>
                                        <dd>{{ $body->translation('en')->first()->created_at }}</dd>
                                        <dt>Last Updated on:</dt>
                                        <dd>{{ $body->translation('en')->first()->updated_at }}</dd>
                                    </dl>
                                    <div class="row">
                                        <div class="col-md-4"></div>
                                        <div class="col-md-4">
                                            <a href="{{ route('body.show', $body->id) }}">
                                                <button type="button" class="btn btn-block btn-info">View</button>
                                            </a>
                                        </div>
                                        <div class="col-md-4">
                                            <a href="{{ route('body.edit', $body->id) }}">
                                                <button type="button" class="btn btn-block btn-primary">Edit</button>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                                <!-- /.box-body -->
                            </div>
                        </div>

                        @php $count++ @endphp

                        @if( $count > $break)
                    </div>
                    @php $count = 1 @endphp
                @endif
            @endforeach

            {{ $bodies->links() }}

        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection

resources/views/admin/pages/body/other_info_edit.blade.php
@extends('admin.master')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Bodies - Other Information Edit
                <small>Control Panel</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ url('/admin') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li><a href="{{ url('/admin/body') }}"><i class="fa fa-dashboard"></i> Bodies</a></li>
                <li class="active"><i class="fa fa-dashboard"></i> edit</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Your Page Content Here -->

            @if(Session::has('message'))
                <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
            @endif

            {!! Form::open(array('url' => '/lgisadminpanel/body/otherinformation/'.$body_id, 'method' => 'post')) !!}
            @include('admin.partials._form_body_other_information_edit')
            {!! Form::close() !!}
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection

resources/views/admin/pages/body/show.blade.php
@extends('admin.master')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Bodies
                <small>Admin-Panel</small>
                {{--<span><a href="{{ url('/admin/province/create') }}"  style="padding-left: 15px;"><i class="fa fa-plus"></i></a></span>--}}
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ url('/lgisadminpannel') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li class="active">{{$bodies->translation('en')->first()->name}}</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <div class="box-body">

                {{ $bodies->translation('en')->first()->name }} <br/>

                {{ $bodies->translation('en')->first()->description  }} <br/>

                {{ $bodies->translation('en')->first()->headquarter  }} <br/>

                {{ $bodies->translation('en')->first()->population  }} <br/>

                {{ $bodies->translation('en')->first()->area  }} <br/>

                {{ $bodies->translation('en')->first()->border  }} <br/>

            </div>

            <div class="row">
                <div class="col-md-4">
                    <a href="{{ route('body.edit', $bodies->id) }}">
                        <button type="button" class="btn btn-block btn-primary">Edit</button>
                    </a>
                </div>

                <div class="col-md-4">
                    <a href="{{ url('lgisadminpanel/body/otherinformation/'. $bodies->id) }}">
                        <button type="button" class="btn btn-block btn-info">Other Information</button>
                    </a>
                </div>
            </div>

        </section><!-- /.content -->
        <section>

            <div class="box-body">
                <h3>List Of Wards<a href="{{ url('lgisadminpanel/ward/create/'. $bodies->id) }}"  style="padding-left: 15px;"><i class="fa fa-plus"></i></a></h3>


            <!-- Your Page Content Here -->
                @php
                    $count = 1;
                    $break = 2;
                @endphp

                @foreach($bodies->ward as $ward)
{{--                    {{dd($ward) }}--}}
                    @if( $count == 1)
                        <div class="row">
                            @endif

                            <div class="col-md-6">
                                <div class="box box-solid">
                                    <div class="box-header with-border">
                                        <i class="fa fa-text-width"></i>
                                        <h3 class="box-title">{{ $ward->name }}</h3>
                                    </div>
                                    <!-- /.box-header -->
                                    <div class="box-body">
                                        <dl class="dl-horizontal">
                                            <dt>Population</dt>
                                            <dd>{{ $ward->population }}</dd>
                                            <dt>Area</dt>
                                            <dd>{{ $ward->area }}</dd>

                                            <dt>Created On:</dt>
                                            <dd>{{ $ward->created_at }}</dd>
                                            <dt>Last Updated on:</dt>
                                            <dd>{{ $ward->updated_at }}</dd>
                                        </dl>
                                        <div class="row">
                                            <div class="col-md-4"></div>
                                            <div class="col-md-4">
                                                <a href="{{ route('body.show', $ward->id) }}">
                                                </a>
                                            </div>
                                            <div class="col-md-4">
                                                <a href="{{ route('ward.edit', $ward->id) }}">
                                                    <button type="button" class="btn btn-block btn-primary">Edit</button>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.box-body -->
                                </div>
                            </div>

                            @php $count++ @endphp

                            @if( $count > $break)
                        </div>
                        @php $count = 1 @endphp
                    @endif
                @endforeach

            </div>
        </section>

    </div><!-- /.content-wrapper -->

@endsection