routes/web.php
<?php
//Route::get('/id_manager','NepalController@id_manager');

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * For Admin Panel
 *
 * */

//Auth::routes();
//Route::get('/welcome', function (){
//    return view('welcome');
//});

//Route::get('lgisadminpanel/login', 'AdminController@login');
Route::get( 'lgisadminpanel/login', ['middleware' => 'guest', 'uses' => 'AdminController@login'] );

Route::post('lgisadminpanel/login', 'AdminController@postLogin');
//Route::post('lgisadminpanel/login/', ['as' => 'lgisadminpanel.login', 'uses' => 'AdminController@postLogin']);

Route::group(['middleware' => 'auth'], function()
{
    Route::get('lgisadminpanel',          				['uses' => 'AdminController@index']				    );
    Route::get('lgisadminpanel/suggestion/{id}','AdminController@detail');
    Route::get('lgisadminpanel/suggestion/delete/{id}','AdminController@delete');

    Route::resource('lgisadminpanel/province', 'AdminProvinceController');
    Route::get('lgisadminpanel/province/get_from_web/{id}','AdminProvinceController@get_data_from_web');

    Route::resource('lgisadminpanel/district', 'AdminDistrictController');
    Route::get('lgisadminpanel/district/get_from_web/{id}','AdminDistrictController@get_data_from_web');

    Route::resource('lgisadminpanel/body', 'AdminBodyController');
    Route::get('lgisadminpanel/body/get_from_web/{id}','AdminBodyController@get_data_from_web');
    Route::get('lgisadminpanel/body/otherinformation/{id}','AdminBodyController@getOtherInformationForm');
    Route::post('lgisadminpanel/body/otherinformation/{id}','AdminBodyController@postOtherInformationForm');


    Route::get('lgisadminpanel/ward/create/{id}', 'AdminWardController@create');
    Route::resource('lgisadminpanel/ward', 'AdminWardController');

});

Route::get('lgisadminpanel/logout', 'AdminController@getLogout');

/*
 * For Web Application
 *
 * */

Route::get('/',function (){
    $locale = Session::get ('locale');
    if(empty($locale)){
        Session::put('locale','en');
        $locale = 'en';
    }
    return redirect('/' . $locale);
});

Route::get('{locale}/contact', function ($locale){
    \App::setLocale($locale);
    return view('app.site.contact');
});

Route::get('{locale}/about', function ($locale){
    \App::setLocale($locale);
    return view('app.site.about');
});

Route::get('{locale}/help', function ($locale){
    \App::setLocale($locale);
    return view('app.site.help');
});

Route::get('/{locale}', 'NepalController@index');
Route::get('/{locale}/body/metro', 'NepalController@getMetro');
Route::get('/{locale}/body/submetro', 'NepalController@getSubMetro');
Route::get('/{locale}/body/munic', 'NepalController@getMunic');
Route::get('/{locale}/body/ruralmunic', 'NepalController@getRuralMuni');

//Route::get('/{locale}/search', 'NepalController@livesearch');

Route::post('/nepal/', ['as' => 'suggestion_store', 'uses' => 'NepalController@store']);

Route::get('{locale}/province','ProvinceController@index');
Route::get('/{locale}/province/{id}','ProvinceController@show');


Route::get('/{locale}/district', 'DistrictController@index');
Route::get('/{locale}/district/{id}', 'DistrictController@show');


Route::get('/{locale}/body', 'BodyController@index');
Route::get('/{locale}/body/{id}', 'BodyController@show');

app/District.php
<?php

namespace App;

use Illuminate\Support\Facades\App;
use Illuminate\Database\Eloquent\Model;
use App\Support\Translateable;

class District extends Model
{
    //This class will force the Translated class into main class
    use Translateable;

    protected $fillable = ['province_id'];

    public function translation($language = null)
    {
        if ($language == null) {
            $language = App::getLocale();
        }
        return $this->hasMany('App\DistrictTranslation')->where('language', '=', $language);
    }

    public function bodies(){
        return $this->hasMany('App\LocalBody','district_id');
    }

    public function province(){
        return $this->belongsTo('App\Province');
    }
}

app/Http/Controllers/DistrictController.php
<?php

namespace App\Http\Controllers;

use App\DistrictTranslation;
use App\Suggestion;
use Illuminate\Http\Request;

use Symfony\Component\DomCrawler\Crawler;
use Goutte\Client;
use GuzzleHttp\Client as GuzzleClient;
use App\District;

class DistrictController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @param $locale
     * @return \Illuminate\Http\Response
     */
    public function index($locale)
    {

        \App::setLocale($locale);

        $districts = District::all();

        $districts = $districts->sort(function($a, $b)
        {
            $a = $a->translation()->first()->name;
            $b = $b->translation()->first()->name;
            //here you can do more complex comparisons
            //when dealing with sub-objects and child models
            if ($a === $b) {
                return 0;
            }
            return ($a > $b) ? 1 : -1;
        });

        $districts = $this::paginate($districts, 5);


        if ( \Request::is('api/*')) {

            //for api fetch all district

            $districts = District::all();

            $district = array();
            foreach ($districts as $d) {
                array_push($district, array(
                        'province_id' => $d->province_id,
                        'district_id' => $d->id,
                        'district_name' => $d->translation()->first()->name,
                        'district_description' => $d->translation()->first()->description,
                        'count_bodies' => count($d->bodies),
                        'count_wards' => $d->bodies->sum('ward_no'),
                    )
                );
            }
            return response()->json($district);
        }

        return view('app.district.index')->with('districts', $districts);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


    }

    /**
     * Display the specified resource.
     *
     * @param $locale
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($locale,$id)
    {

        \App::setLocale($locale);

        $district = District::findOrFail($id);
        $bodies = $district->bodies;

        if (\Request::is('api/*')) {

            $district_details = array();
            array_push($district_details, array(
                    'district_id' => $district->id,
                    'province_id' => $district->province_id,
                    'district_name' => $district->translation()->first()->name,
                    'district_description' => $district->translation()->first()->description,
                    'ward_count' => $bodies->sum('ward_no'),
                    'bodies' => $bodies,
                )
            );

            return response()->json($district_details);
        }

        return view('app.district.details')->with('district', $district);

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    function paginate($items, $perPage)
    {
        $pageStart = request('page', 1);
        $offSet    = ($pageStart * $perPage) - $perPage;
        $itemsForCurrentPage = $items->slice($offSet, $perPage);

        return new \Illuminate\Pagination\LengthAwarePaginator(
            $itemsForCurrentPage, $items->count(), $perPage,
            \Illuminate\Pagination\Paginator::resolveCurrentPage(),
            ['path' => \Illuminate\Pagination\Paginator::resolveCurrentPath()]
        );
    }

    public function areaOfBodies($id){

        if ( \Request::is('api/*')) {

            $district = District::findOrFail($id);
            $bodies = $district->bodies;

            $data = array();

            foreach ($bodies as $body) {
                array_push($data, array(
                    'name' => $body->translation('en')->first()->name,
                    'area' => (double) $body->translation('en')->first()->area
                ));
            }

            return response()->json($data);
        }
    }

    public function populationOfBodies($id){
        if ( \Request::is('api/*')) {
            $district = District::findOrFail($id);
            $bodies = $district->bodies;

            $data = array();

            foreach ($bodies as $body) {
                array_push($data, array(
                    'name' => $body->translation('en')->first()->name,
                    'population' => (double) $body->translation('en')->first()->population
                ));
            }
            return response()->json($data);
        }
    }

    public function populationOfMaleAndFemale($id){
        if ( \Request::is('api/*')) {
            $district = District::findOrFail($id);

            $data = array();
            array_push($data,[
                'name' => 'Male Population',
                'population' => (double) $district->translation('en')->first()->male_population
            ]);

            array_push($data,[
                'name' => 'Female Population',
                'population' => (double) $district->translation('en')->first()->female_population
            ]);

            return response()->json($data);
        }
    }

    public function populationOfDistrictAndProvince($id){
        if ( \Request::is('api/*')) {
            $district = District::findOrFail($id);

            $data = array();
            array_push($data,[
                'name' => 'Population of Province',
                'population' => (double) $district->province->translation('en')->first()->population
            ]);

            array_push($data,[
                'name' => 'Population of District',
                'population' => (double) $district->translation('en')->first()->population
            ]);

            return response()->json($data);
        }
    }

    public function areaOfDistrictAndProvince($id){
        if ( \Request::is('api/*')) {
            $district = District::findOrFail($id);

            $data = array();
            array_push($data,[
                'name' => 'Area of Province',
                'area' => (double) $district->province->translation('en')->first()->area
            ]);

            array_push($data,[
                'name' => 'Area of District',
                'area' => (double) $district->translation('en')->first()->area
            ]);

            return response()->json($data);
        }
    }
}

resources/views/admin/pages/district/create.blade.php
@extends('admin.master')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Province - Create
                <small>Control Panel</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ url('/admin') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li><a href="{{ url('/admin/province') }}"><i class="fa fa-dashboard"></i> Province</a></li>
                <li class="active"><i class="fa fa-dashboard"></i> create</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Your Page Content Here -->

            <div class="row">
                <div class="col-md-6">
                    <p class="text-center">In English</p>
                </div>

                <div class="col-md-6">
                    <p class="text-center">In Nepali</p>
                </div>
            </div>

            <form role="form">
                <div class="box-body">

                    <div class="form-group">
                        <label> Name</label>
                        <div class="row">
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="name" placeholder="Enter the Name">
                            </div>

                            <div class="col-md-6">
                                <input type="text" class="form-control" id="name" placeholder="Name will be Converted in Nepali">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label> Description</label>
                        <div class="row">
                            <div class="col-md-6">
                                <textarea class="form-control" rows="6" placeholder="Enter the Description in English"></textarea>
                            </div>

                            <div class="col-md-6">
                                <textarea class="form-control" rows="6" placeholder="The description will be converted in Nepali"></textarea>
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label> Population</label>
                        <div class="row">
                            <div class="col-md-6">
                                <input type="number" class="form-control" id="population" placeholder="Population">
                            </div>

                            <div class="col-md-6">
                                <input type="text" class="form-control" id="population" placeholder="Population">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label> Area(in km<sup>2</sup>)</label>
                        <div class="row">
                            <div class="col-md-6">
                                <input type="number" class="form-control" id="population" placeholder="Area">
                            </div>

                            <div class="col-md-6">
                                <input type="text" class="form-control" id="population" placeholder="Area">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label> Density(per km<sup>2</sup>)</label>
                        <div class="row">
                            <div class="col-md-6">
                                <input type="number" class="form-control" id="population" placeholder="Density">
                            </div>

                            <div class="col-md-6">
                                <input type="text" class="form-control" id="population" placeholder="Density">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label> Border</label>
                        <div class="row">
                            <div class="col-md-6">
                                <h5> East</h5>
                                <input type="text" class="form-control" id="population" placeholder="East Border">
                                <h5> West</h5>
                                <input type="text" class="form-control" id="population" placeholder="West Border">
                                <h5> South</h5>
                                <input type="text" class="form-control" id="population" placeholder="South Border">
                                <h5> North</h5>
                                <input type="text" class="form-control" id="population" placeholder="North Border">
                            </div>

                            <div class="col-md-6">
                                <h5> East</h5>
                                <input type="text" class="form-control" id="population" placeholder="East Border">
                                <h5> West</h5>
                                <input type="text" class="form-control" id="population" placeholder="West Border">
                                <h5> South</h5>
                                <input type="text" class="form-control" id="population" placeholder="South Border">
                                <h5> North</h5>
                                <input type="text" class="form-control" id="population" placeholder="North Border">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label> Headquaters</label>
                        <div class="row">
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="population" placeholder="Headquater">
                            </div>

                            <div class="col-md-6">
                                <input type="text" class="form-control" id="population" placeholder="headquater">
                            </div>
                        </div>
                    </div>

                    <div class="form-group">
                        <label> Mix</label>
                        <div class="row">
                            <div class="col-md-6">
                                <input type="text" class="form-control" id="population" placeholder="Mix">
                            </div>

                            <div class="col-md-6">
                                <input type="text" class="form-control" id="population" placeholder="Mix">
                            </div>
                        </div>
                    </div>

                </div>

                <div class="box-footer">
                    <button type="submit" class="btn btn-danger">Cancel</button>
                    <button type="submit" class="btn btn-info">Convert English to Nepali</button>
                    <button type="submit" class="btn btn-primary pull-right">Save Changes</button>
                </div>

            </form>
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection

resources/views/admin/pages/district/edit.blade.php
@extends('admin.master')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Districts - Edit
                <small>Control Panel</small>
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ url('/admin') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li><a href="{{ url('/admin/district') }}"><i class="fa fa-dashboard"></i> Districts</a></li>
                <li class="active"><i class="fa fa-dashboard"></i> edit</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            @if(Session::has('message'))
                <p class="alert {{ Session::get('alert-class', 'alert-info') }}">{{ Session::get('message') }}</p>
            @endif

            <!-- Your Page Content Here -->

            <div class="row">
                <div class="col-md-6">
                    <p class="text-center">In English</p>
                </div>

                <div class="col-md-6">
                    <p class="text-center">In Nepali</p>
                </div>
            </div>

            {!! Form::model($district, ['method' => 'PATCH', 'enctype' => 'multipart/form-data' ,'route' => ['district.update', $district->id] ]) !!}
            @include('admin.partials._form_district_edit')
            {!! Form::close() !!}
        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection

resources/views/admin/pages/district/index.blade.php
@extends('admin.master')

@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Districts
                <small>Admin-Panel</small>
                {{--<span><a href="{{ url('/admin/district/create') }}"  style="padding-left: 15px;"><i class="fa fa-plus"></i></a></span>--}}
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ url('/admin') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li class="active">Districts</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <!-- Your Page Content Here -->
            @php
                 $count = 1;
                 $break = 2;
            @endphp

                @foreach($districts as $district)
                    @if( $count == 1)
                        <div class="row">
                    @endif

                            <div class="col-md-6">
                                <div class="box box-solid">
                                    <div class="box-header with-border">
                                        <i class="fa fa-text-width"></i>
                                        <h3 class="box-title">{{ $district->translation('en')->first()->name }}</h3>
                                    </div>
                                    <!-- /.box-header -->
                                    <div class="box-body">
                                        <dl class="dl-horizontal">
                                            <dt>Description</dt>
                                            <dd>Some Descp.</dd>
                                            <dt>Created On:</dt>
                                            <dd>Random Time</dd>
                                            <dt>Last Updated on:</dt>
                                            <dd>Some Random Time</dd>
                                        </dl>
                                        <div class="row">
                                            <div class="col-md-4"></div>
                                            <div class="col-md-4">
                                                <a href="{{ route('district.show', $district->id) }}">
                                                    <button type="button" class="btn btn-block btn-info">View</button>
                                                </a>
                                            </div>
                                            <div class="col-md-4">
                                                <a href="{{ route('district.edit', $district->id) }}">
                                                    <button type="button" class="btn btn-block btn-primary">Edit</button>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.box-body -->
                                </div>
                            </div>

                    @php $count++ @endphp

                    @if( $count > $break)
                        </div>
                        @php $count = 1 @endphp
                    @endif
                @endforeach

            {{ $districts->links() }}

        </section><!-- /.content -->
    </div><!-- /.content-wrapper -->
@endsection

resources/views/admin/pages/district/show.blade.php
@extends('admin.master')
{{--{{ dd($district->translation('en')->first()->name) }}--}}
@section('content')
    <!-- Content Wrapper. Contains page content -->
    <div class="content-wrapper">
        <!-- Content Header (Page header) -->
        <section class="content-header">
            <h1>
                Districts
                <small>Admin-Panel</small>
                {{--<span><a href="{{ url('/admin/province/create') }}"  style="padding-left: 15px;"><i class="fa fa-plus"></i></a></span>--}}
            </h1>
            <ol class="breadcrumb">
                <li><a href="{{ url('/lgisadminpannel') }}"><i class="fa fa-dashboard"></i> Dashboard</a></li>
                <li class="active">{{$district->translation('en')->first()->name}}</li>
            </ol>
        </section>

        <!-- Main content -->
        <section class="content">

            <div class="box-body">

                {{ $district->translation('en')->first()->name }} <br/>

                {{ $district->translation('en')->first()->description  }} <br/>

                {{ $district->translation('en')->first()->headquarter  }} <br/>

                {{ $district->translation('en')->first()->population  }} <br/>

                {{ $district->translation('en')->first()->area  }} <br/>

                {{ $district->translation('en')->first()->border  }} <br/>

            </div>

            <div class="col-md-4">
                <a href="{{ route('district.edit', $district->id) }}">
                    <button type="button" class="btn btn-block btn-primary">Edit</button>
                </a>
            </div>

        </section><!-- /.content -->

        <section>
            <div class="box-body">

                <!-- Your Page Content Here -->
                @php
                    $count = 1;
                    $break = 2;
                @endphp

                @foreach($district->bodies as $body)
                    @if( $count == 1)
                        <div class="row">
                            @endif

                            <div class="col-md-6">
                                <div class="box box-solid">
                                    <div class="box-header with-border">
                                        <i class="fa fa-text-width"></i>
                                        <h3 class="box-title">{{ $body->translation('en')->first()->name }}</h3>
                                    </div>
                                    <!-- /.box-header -->
                                    <div class="box-body">
                                        <dl class="dl-horizontal">
                                            <dt>Description</dt>
                                            <dd>{{ $body->translation('en')->first()->description }}</dd>
                                            <dt>Created On:</dt>
                                            <dd>{{ $body->translation('en')->first()->created_at }}</dd>
                                            <dt>Last Updated on:</dt>
                                            <dd>{{ $body->translation('en')->first()->updated_at }}</dd>
                                        </dl>
                                        <div class="row">
                                            <div class="col-md-4"></div>
                                            <div class="col-md-4">
                                                <a href="{{ route('body.show', $body->id) }}">
                                                    <button type="button" class="btn btn-block btn-info">View</button>
                                                </a>
                                            </div>
                                            <div class="col-md-4">
                                                <a href="{{ route('body.edit', $body->id) }}">
                                                    <button type="button" class="btn btn-block btn-primary">Edit</button>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- /.box-body -->
                                </div>
                            </div>

                            @php $count++ @endphp

                            @if( $count > $break)
                        </div>
                        @php $count = 1 @endphp
                    @endif
                @endforeach

            </div>
        </section>

    </div><!-- /.content-wrapper -->
@endsection