routes/web.php
<?php
//Route::get('/id_manager','NepalController@id_manager');

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

/*
 * For Admin Panel
 *
 * */

//Auth::routes();
//Route::get('/welcome', function (){
//    return view('welcome');
//});

//Route::get('lgisadminpanel/login', 'AdminController@login');
Route::get( 'lgisadminpanel/login', ['middleware' => 'guest', 'uses' => 'AdminController@login'] );

Route::post('lgisadminpanel/login', 'AdminController@postLogin');
//Route::post('lgisadminpanel/login/', ['as' => 'lgisadminpanel.login', 'uses' => 'AdminController@postLogin']);

Route::group(['middleware' => 'auth'], function()
{
    Route::get('lgisadminpanel',          				['uses' => 'AdminController@index']				    );
    Route::get('lgisadminpanel/suggestion/{id}','AdminController@detail');
    Route::get('lgisadminpanel/suggestion/delete/{id}','AdminController@delete');

    Route::resource('lgisadminpanel/province', 'AdminProvinceController');
    Route::get('lgisadminpanel/province/get_from_web/{id}','AdminProvinceController@get_data_from_web');

    Route::resource('lgisadminpanel/district', 'AdminDistrictController');
    Route::get('lgisadminpanel/district/get_from_web/{id}','AdminDistrictController@get_data_from_web');

    Route::resource('lgisadminpanel/body', 'AdminBodyController');
    Route::get('lgisadminpanel/body/get_from_web/{id}','AdminBodyController@get_data_from_web');
    Route::get('lgisadminpanel/body/otherinformation/{id}','AdminBodyController@getOtherInformationForm');
    Route::post('lgisadminpanel/body/otherinformation/{id}','AdminBodyController@postOtherInformationForm');


    Route::get('lgisadminpanel/ward/create/{id}', 'AdminWardController@create');
    Route::resource('lgisadminpanel/ward', 'AdminWardController');

});

Route::get('lgisadminpanel/logout', 'AdminController@getLogout');

/*
 * For Web Application
 *
 * */

Route::get('/',function (){
    $locale = Session::get ('locale');
    if(empty($locale)){
        Session::put('locale','en');
        $locale = 'en';
    }
    return redirect('/' . $locale);
});

Route::get('{locale}/contact', function ($locale){
    \App::setLocale($locale);
    return view('app.site.contact');
});

Route::get('{locale}/about', function ($locale){
    \App::setLocale($locale);
    return view('app.site.about');
});

Route::get('{locale}/help', function ($locale){
    \App::setLocale($locale);
    return view('app.site.help');
});

Route::get('/{locale}', 'NepalController@index');
Route::get('/{locale}/body/metro', 'NepalController@getMetro');
Route::get('/{locale}/body/submetro', 'NepalController@getSubMetro');
Route::get('/{locale}/body/munic', 'NepalController@getMunic');
Route::get('/{locale}/body/ruralmunic', 'NepalController@getRuralMuni');

//Route::get('/{locale}/search', 'NepalController@livesearch');

Route::post('/nepal/', ['as' => 'suggestion_store', 'uses' => 'NepalController@store']);

Route::get('{locale}/province','ProvinceController@index');
Route::get('/{locale}/province/{id}','ProvinceController@show');


Route::get('/{locale}/district', 'DistrictController@index');
Route::get('/{locale}/district/{id}', 'DistrictController@show');


Route::get('/{locale}/body', 'BodyController@index');
Route::get('/{locale}/body/{id}', 'BodyController@show');

resources/views/admin/partials/_footer.blade.php
<!-- Main Footer -->
<footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
        Managed By Our Company
    </div>
    <!-- Default to the left -->
    <strong>Copyright © 2017 <a href="{{url('/')}}">LGIS</a>.</strong> All rights reserved.
</footer>

resources/views/admin/partials/_form_body_create.blade.php
<div class="box-body">

    <div class="row">

        <div class="col-md-12 dropdown">
            <select name="district_id">
                @foreach($districts as $district)
                    {{--{{ dd($district->id) }}--}}
                    <option value="{{ $district->id }}">{{ $district->translation('en')->first()->name  }}</option>
                @endforeach
            </select>
        </div>
    </div>

    <div class="form-group">
        <label> Name</label>
        <div class="row">
            <div class="col-md-6">
                <input required type="text" class="form-control" name="name" value="" placeholder="Enter the Name">
            </div>

            <div class="col-md-6">
                <input required  type="text" class="form-control" name="name_ne" value="" placeholder="Name will be Converted in Nepali">
            </div>
        </div>
    </div>

    <div class="form-group">
        <label> Description</label>
        <div class="row">
            <div class="col-md-6">

                <textarea  required class="form-control" name="description" rows="6" placeholder="Enter the Description in English"></textarea>

            </div>

            <div class="col-md-6">
                <textarea required  class="form-control" name="description_ne" rows="6" placeholder="The description will be converted in Nepali"></textarea>
            </div>
        </div>
    </div>
    <div class="form-group">
        <label> Type</label>
        <div class="row">
            <div class="col-md-12 dropdown">
                <select class="admin-select" name="type">
                    {{--{{ dd($district->id) }}--}}
                    <option value="municipality">municipality</option>
                    <option value="rural_municipality">rural_municipality</option>
                    <option value="sub_metro">sub_metro</option>
                    <option value="metro">metro</option>
                </select>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div class="row">
            <div class="col-md-12">
                <label> Number of wards</label>
                <input required  type="text" class="form-control"  value=""  name="ward_no" placeholder="Enter number of wards">
            </div>
        </div>
    </div>
    <div class="form-group">
        <label> Map </label>
        <div class="row">
            <div class="col-md-12">
                <input type="file" class="form-control"  value=""  name="map_upload" placeholder="Upload Map">
            </div>
        </div>
    </div>

    <div class="form-group">
        <label> People's Representative :- </label>
        <div class="row">
            <div class="col-md-12">
                <label> Mayor:</label><br>
                <label> Name</label>
                <input  required type="text" class="form-control"  value=""  name="mayor_name" placeholder="Enter mayor name">
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <label> Email</label>
                <input required  type="text" class="form-control"  value=""  name="mayor_email" placeholder="Enter mayor email">
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <label> Phone</label>
                <input required  type="text" class="form-control"  value=""  name="mayor_phone" placeholder="Enter mayor Phone number">
            </div>


        </div>
        <div class="row">
            <div class="col-md-12">
                <label> Photo</label>
                <input type="file" class="form-control"  value=""  name="mayor_photo" placeholder="Enter mayor Phone number">
            </div>
        </div>
        <br>
        <div class="row">
            <div class="col-md-12">
                <label> Deputy Mayor:</label><br>
                <label> Name</label>

                <input  required type="text" class="form-control"  value=""  name="deputy_mayor_name" placeholder="Enter Deputy mayor name">
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <label> Email</label>
                <input required  type="text" class="form-control"  value=""  name="deputy_mayor_email" placeholder="Enter deputy mayor Email">
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <label> Phone</label>
                <input  required type="text" class="form-control"  value=""  name="deputy_mayor_phone" placeholder="Enter deputy mayor Phone number">
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <label> Photo</label>
                <input type="file" class="form-control"  value=""  name="deputy_mayor_photo" placeholder="Enter mayor Phone number">
            </div>

        </div>
    </div>

    <div class="form-group">
        <label> Population</label>
        <div class="row">
            <div class="col-md-12">
                <label> Male</label>
                <input  required type="text" class="form-control"  value=""  name="male_population" placeholder="Population of male">
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <label> Female</label>
                <input required  type="text" class="form-control"  value=""  name="female_population" placeholder="Population of female">
            </div>

        </div>

    </div>


    <div class="form-group">
        <label> Area(in km<sup>2</sup>)</label>
        <div class="row">
            <div class="col-md-12">
                <input  required type="text" class="form-control" value=""  name="area" placeholder="Area">
            </div>

        </div>
    </div>

    <div class="form-group">
        <label> Density(per km<sup>2</sup>)</label>
        <div class="row">
            <div class="col-md-12">
                <input  required type="text" class="form-control" value="" name="density" placeholder="Density">
            </div>

        </div>
    </div>


    {{--@php--}}

    {{--$border = explode(";", $body->translation('en')->first()->border);--}}

    {{--$east = explode(":",$border[0])[1];--}}
    {{--$west = explode(":",$border[1])[1];--}}
    {{--$south = explode(":",$border[2])[1];--}}
    {{--$north = explode(":",$border[3])[1];--}}

    {{--$border_ne = explode(";", $body->translation('ne')->first()->border);--}}

    {{--$east_ne = explode(":",$border_ne[0])[1];--}}
    {{--$west_ne = explode(":",$border_ne[1])[1];--}}
    {{--$south_ne = explode(":",$border_ne[2])[1];--}}
    {{--$north_ne = explode(":",$border_ne[3])[1];--}}


    {{--@endphp--}}

    {{--<div class="form-group">--}}
    {{--<label> Border</label>--}}
    {{--<div class="row">--}}
    {{--<div class="col-md-6">--}}
    {{--<h5> East</h5>--}}
    {{--<input type="text" class="form-control" value="{{ $east }}" name="east_border" placeholder="East Border">--}}
    {{--<h5> West</h5>--}}
    {{--<input type="text" class="form-control" value="{{ $west }}" name="west_border" placeholder="West Border">--}}
    {{--<h5> South</h5>--}}
    {{--<input type="text" class="form-control" value="{{ $south }}" name="south_border" placeholder="South Border">--}}
    {{--<h5> North</h5>--}}
    {{--<input type="text" class="form-control" value="{{ $north }}" name="north_border" placeholder="North Border">--}}
    {{--</div>--}}

    {{--<div class="col-md-6">--}}
    {{--<h5> East</h5>--}}
    {{--<input type="text" class="form-control" value="{{ $east_ne }}" name="east_border_ne" placeholder="East Border">--}}
    {{--<h5> West</h5>--}}
    {{--<input type="text" class="form-control" value="{{ $west_ne }}" name="west_border_ne" placeholder="West Border">--}}
    {{--<h5> South</h5>--}}
    {{--<input type="text" class="form-control" value="{{ $south_ne }}" name="south_border_ne" placeholder="South Border">--}}
    {{--<h5> North</h5>--}}
    {{--<input type="text" class="form-control" value="{{ $north_ne }}" name="north_border_ne" placeholder="North Border">--}}
    {{--</div>--}}
    {{--</div>--}}
    {{--</div>--}}

    <div class="form-group">
        <label> Headquarters</label>
        <div class="row">
            <div class="col-md-6">
                <input required  type="text" class="form-control" value="" name="headquarter" placeholder="Headquater">
            </div>

            <div class="col-md-6">
                <input  required type="text" class="form-control" value="" name="headquarter_ne" placeholder="headquater">
            </div>
        </div>
    </div>
</div>

<div class="box-footer">
    <div class="btn btn-danger"><a href="{{ route('body.index') }}" style="color: white">Cancel</a></div>
    {{--<div class="btn btn-info">Pull data from web</div>--}}
    <button type="submit" class="btn btn-primary pull-right">Save Changes</button>

</div>

resources/views/admin/partials/_form_body_edit.blade.php
<div class="box-body">

    <div class="form-group">
        <label> Name</label>
        <div class="row">
            <div class="col-md-6">
                <input type="text"  required class="form-control" name="name" value="{{$body->translation('en')->first()->name }}" placeholder="Enter the Name">
            </div>

            <div class="col-md-6">
                <input type="text"  required class="form-control" name="name_ne" value="{{ $body->translation('ne')->first()->name }}" placeholder="Name will be Converted in Nepali">
            </div>
        </div>
    </div>

    <div class="form-group">
        <label> Description</label>
        <div class="row">
            <div class="col-md-6">
                @if(!isset($en_body_info))
                    <textarea class="form-control" required  name="description" rows="6" placeholder="Enter the Description in English">{{ $body->translation('en')->first()->description}}</textarea>
                @else
                    <textarea class="form-control" required  name="description" rows="6" placeholder="Enter the Description in English">
                          @if(isset($en_body_info[1]))
                            {{ $en_body_info[1]}}
                        @else
                            {{ "No data found" }}
                        @endif

                    </textarea>
                @endif
            </div>

            <div class="col-md-6">
                @if(!isset($ne_body_info))
                <textarea class="form-control"  required name="description_ne" rows="6"  placeholder="The description will be converted in Nepali">{{ $body->translation('ne')->first()->description}}</textarea>
                @else
                    <textarea class="form-control" required  name="description_ne" rows="6" placeholder="The description will be converted in Nepali">
                        @if(isset($ne_body_info[0]))
                            {{ $ne_body_info[0]}}
                        @else
                            {{ "No data found" }}
                        @endif

                    </textarea>
                @endif
            </div>
        </div>
    </div>

    <div class="form-group">
        <label> Map </label>
        <div class="row">
            <div class="col-md-12">
                <input type="file" class="form-control"  value=""  name="map_upload" placeholder="Upload Map">
            </div>
        </div>
    </div>

    <div class="form-group">
        <label> People's Representative :- </label>
        <div class="row">
            <div class="col-md-12">
                <label> Mayor:</label><br>
                <label> Name</label>
                @if(isset($representaive_name[0]))
                    <input type="text"  required class="form-control"  value="{{ $representaive_name[0] }}"  name="mayor_name" placeholder="Enter mayor name">
                @else
                    <input type="text"  required class="form-control"  value="{{ $body->representative->mayor_name or ""}}"  name="mayor_name" placeholder="Enter mayor name">
                @endif
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <label> Email</label>
            @if(isset($representaive_email[0]))
                    <input type="text"  required class="form-control"  value="{{ $representaive_email[0] }}"  name="mayor_email" placeholder="Enter mayor email">
                @else
                    <input type="text"  required class="form-control"  value="{{ $body->representative->mayor_email  or ""}}"  name="mayor_email" placeholder="Enter mayor email">
                @endif
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <label> Phone</label>
            @if(isset($representaive_phone[0]))
                    <input type="text"  required class="form-control"  value="{{ $representative_phone[0] }}"  name="mayor_phone" placeholder="Enter mayor Phone number">
                @else
                    <input type="text"  required class="form-control"  value="{{ $body->representative->mayor_phone or ""}}"  name="mayor_phone" placeholder="Enter mayor Phone number">
                @endif
            </div>


        </div>
        <div class="row">
            <div class="col-md-12">
                <label> Photo</label>
                {{--@if(isset($body->representative->mayor_pic))--}}
                    {{--<img src="{{ $body->representative->mayor_pic }}" />--}}
                {{--@else--}}
                <input type="file"  class="form-control"  value="{{ $body->representative->mayor_pic or "" }}"  name="mayor_photo" >
                {{--@endif--}}
            </div>
        </div>
        <br>
        <div class="row">
        <div class="col-md-12">
            <label> Deputy Mayor:</label><br>
            <label> Name</label>
            @if(isset($representaive_name[1]))
                <input type="text"  required class="form-control"  value="{{ $representaive_name[1] }}"  name="deputy_mayor_name" placeholder="Enter Deputy mayor name">
            @else
                <input type="text"  required class="form-control"  value="{{ $body->representative->deputy_name or "" }}"  name="deputy_mayor_name" placeholder="Enter Deputy mayor name">
            @endif
        </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <label> Email</label>
                @if(isset($representaive_email[1]))
                    <input type="text"  required class="form-control"  value="{{ $representaive_email[1] }}"  name="deputy_mayor_email" placeholder="Enter deputy mayor Email">
                @else
                    <input type="text"  required class="form-control"  value="{{ $body->representative->deputy_email or "" }}"  name="deputy_mayor_email" placeholder="Enter deputy mayor Email">
                @endif
            </div>
        </div>

        <div class="row">
            <div class="col-md-12">
                <label> Phone</label>
                @if(isset($representative_phone[1]))
                    <input type="text"  required class="form-control"  value="{{ $representative_phone[1] }}"  name="deputy_mayor_phone" placeholder="Enter deputy mayor Phone number">
                @else
                    <input type="text"  required class="form-control"  value="{{ $body->representative->deputy_phone or "" }}"  name="deputy_mayor_phone" placeholder="Enter deputy mayor Phone number">
                @endif
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <label> Photo</label>
                {{--@if(isset($body->representative->deputy_pic))--}}
                    {{--<img src="{{ $body->representative->deputy_pic }}" />--}}
                {{--@else--}}
                <input type="file"  required class="form-control"  value="{{ $body->representative->deputy_pic or "" }}"  name="deputy_mayor_photo" placeholder="Enter mayor Phone number">
                {{--@endif--}}
            </div>

        </div>
    </div>

    <div class="form-group">
        <label> Population</label>
        <div class="row">
            <div class="col-md-12">
                <label> Population </label>
                <input type="text" required class="form-control"  value="{{ $body->translation('en')->first()->population or "0" }}"  name="population" placeholder="Total Population">
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <label> Male</label>
                <input type="text" required class="form-control"  value="{{ $body->translation('en')->first()->male_population or "0" }}"  name="male_population" placeholder="Population of male">
            </div>

        </div>
        <div class="row">
            <div class="col-md-12">
                <label> Female</label>
                <input type="text" required class="form-control"  value="{{ $body->translation('en')->first()->male_population or "0" }}"  name="female_population" placeholder="Population of female">
            </div>

        </div>

    </div>


    <div class="form-group">
        <label> Area(in km<sup>2</sup>)</label>
        <div class="row">
            <div class="col-md-12">
                <input type="text"  required class="form-control" value="{{ $body->translation('en')->first()->area }}"  name="area" placeholder="Area">
            </div>

        </div>
    </div>

    <div class="form-group">
        <label> Density(per km<sup>2</sup>)</label>
        <div class="row">
            <div class="col-md-12">
                <input type="text"  required class="form-control" value="{{ $body->translation('en')->first()->density }}" name="density" placeholder="Density">
            </div>

        </div>
    </div>


    {{--@php--}}

        {{--$border = explode(";", $body->translation('en')->first()->border);--}}

        {{--$east = explode(":",$border[0])[1];--}}
        {{--$west = explode(":",$border[1])[1];--}}
        {{--$south = explode(":",$border[2])[1];--}}
        {{--$north = explode(":",$border[3])[1];--}}

        {{--$border_ne = explode(";", $body->translation('ne')->first()->border);--}}

        {{--$east_ne = explode(":",$border_ne[0])[1];--}}
        {{--$west_ne = explode(":",$border_ne[1])[1];--}}
        {{--$south_ne = explode(":",$border_ne[2])[1];--}}
        {{--$north_ne = explode(":",$border_ne[3])[1];--}}


    {{--@endphp--}}

    {{--<div class="form-group">--}}
        {{--<label> Border</label>--}}
        {{--<div class="row">--}}
            {{--<div class="col-md-6">--}}
                {{--<h5> East</h5>--}}
                {{--<input type="text" class="form-control" value="{{ $east }}" name="east_border" placeholder="East Border">--}}
                {{--<h5> West</h5>--}}
                {{--<input type="text" class="form-control" value="{{ $west }}" name="west_border" placeholder="West Border">--}}
                {{--<h5> South</h5>--}}
                {{--<input type="text" class="form-control" value="{{ $south }}" name="south_border" placeholder="South Border">--}}
                {{--<h5> North</h5>--}}
                {{--<input type="text" class="form-control" value="{{ $north }}" name="north_border" placeholder="North Border">--}}
            {{--</div>--}}

            {{--<div class="col-md-6">--}}
                {{--<h5> East</h5>--}}
                {{--<input type="text" class="form-control" value="{{ $east_ne }}" name="east_border_ne" placeholder="East Border">--}}
                {{--<h5> West</h5>--}}
                {{--<input type="text" class="form-control" value="{{ $west_ne }}" name="west_border_ne" placeholder="West Border">--}}
                {{--<h5> South</h5>--}}
                {{--<input type="text" class="form-control" value="{{ $south_ne }}" name="south_border_ne" placeholder="South Border">--}}
                {{--<h5> North</h5>--}}
                {{--<input type="text" class="form-control" value="{{ $north_ne }}" name="north_border_ne" placeholder="North Border">--}}
            {{--</div>--}}
        {{--</div>--}}
    {{--</div>--}}

    <div class="form-group">
        <label> Headquarters</label>
        <div class="row">
            <div class="col-md-6">
                <input type="text"  required class="form-control" value="{{ $body->translation('en')->first()->headquarter }}" name="headquarter" placeholder="Headquater">
            </div>

            <div class="col-md-6">
                <input type="text"  required class="form-control" value="{{ $body->translation('ne')->first()->headquarter }}" name="headquarter_ne" placeholder="headquater">
            </div>
        </div>
    </div>
</div>

<div class="box-footer">
    <div class="btn btn-danger"><a href="{{ route('body.index') }}" style="color: white">Cancel</a></div>
    {{--<div class="btn btn-info">Pull data from web</div>--}}
    <a href="{{ url('lgisadminpanel/body/get_from_web/'.$body->id) }}" class="btn btn-info">Pull data from web</a>
    <button type="submit" class="btn btn-primary pull-right">Save Changes</button>
</div>

resources/views/admin/partials/_form_province_create.blade.php
<div class="box-body">

    <div class="form-group">
        <label> Name</label>
        <div class="row">
            <div class="col-md-6">
                <input type="text"  required class="form-control" name="name" placeholder="Enter the Name">
            </div>

            <div class="col-md-6">
                <input type="text"  required class="form-control" name="name_ne" placeholder="Name will be Converted in Nepali">
            </div>
        </div>
    </div>

    <div class="form-group">
        <label> Description</label>
        <div class="row">
            <div class="col-md-6">
                <textarea class="form-control" required  name="description" rows="6" placeholder="Enter the Description in English"></textarea>
            </div>

            <div class="col-md-6">
                <textarea class="form-control" required  name="description_ne" rows="6"  placeholder="The description will be converted in Nepali"></textarea>
            </div>
        </div>
    </div>

    <div class="form-group">
        <label> Population</label>
        <div class="row">
            <div class="col-md-6">
                <input type="text" required  class="form-control"  name="population" placeholder="Population">
            </div>

            <div class="col-md-6">
                <input type="text" required  class="form-control" name="population_ne" placeholder="Population">
            </div>
        </div>
    </div>

    <div class="form-group">
        <label> Area(in km<sup>2</sup>)</label>
        <div class="row">
            <div class="col-md-6">
                <input type="text"  required class="form-control" name="area" placeholder="Area">
            </div>

            <div class="col-md-6">
                <input type="text" required  class="form-control" name="area_ne" placeholder="Area">
            </div>
        </div>
    </div>

    <div class="form-group">
        <label> Density(per km<sup>2</sup>)</label>
        <div class="row">
            <div class="col-md-6">
                <input type="text" required class="form-control" name="density" placeholder="Density">
            </div>

            <div class="col-md-6">
                <input type="text"  required class="form-control" name="density_ne" placeholder="Density">
            </div>
        </div>
    </div>

    <div class="form-group">
        <label> Border</label>
        <div class="row">
            <div class="col-md-6">
                <h5> East</h5>
                <input type="text"  required class="form-control" placeholder="East Border">
                <h5> West</h5>
                <input type="text"  required class="form-control"  placeholder="West Border">
                <h5> South</h5>
                <input type="text"  required class="form-control" placeholder="South Border">
                <h5> North</h5>
                <input type="text"  required class="form-control" placeholder="North Border">
            </div>

            <div class="col-md-6">
                <h5> East</h5>
                <input type="text"  required class="form-control"  name="east_border_ne" placeholder="East Border">
                <h5> West</h5>
                <input type="text"  required class="form-control"  name="west_border_ne" placeholder="West Border">
                <h5> South</h5>
                <input type="text"  required class="form-control"  name="south_border_ne" placeholder="South Border">
                <h5> North</h5>
                <input type="text"  required class="form-control"  name="north_border_ne" placeholder="North Border">
            </div>
        </div>
    </div>

    <div class="form-group">
        <label> Headquarters</label>
        <div class="row">
            <div class="col-md-6">
                <input type="text"  required class="form-control"  name="headquarter" placeholder="Headquater">
            </div>

            <div class="col-md-6">
                <input type="text"  required class="form-control"  name="headquarter_ne" placeholder="headquater">
            </div>
        </div>
    </div>

</div>

<div class="box-footer">
    <div class="btn btn-danger"><a href="{{ route('province.index') }}" style="color: white">Cancel</a></div>
    <div class="btn btn-info">Convert English to Nepali</div>
    <button type="submit" class="btn btn-primary pull-right">Save Changes</button>
</div>

resources/views/admin/partials/_form_ward_create.blade.php
<div class="box-body">

    <div class="form-group">
        <label> Name</label>
        <div class="row">
            <div class="col-md-12">
                <input type="text" required class="form-control" name="name" value="" placeholder="Enter the Name">
            </div>
        </div>
    </div>
    <div class="form-group">
        <label>Ward ID</label>
        <div class="row">
            <div class="col-md-12">
                <input type="number"  required class="form-control" name="ward_id" value="" placeholder="Enter the ID of ward">
            </div>
        </div>
    </div>
    <div class="form-group">
        <label> Population</label>
        <div class="row">
            <div class="col-md-12">
                <input type="text" required class="form-control" name="population" value="" placeholder="Enter the Population">
            </div>
        </div>
    </div>
    <div class="form-group">
        <label> Area</label>
        <div class="row">
            <div class="col-md-12">
                <input type="text" required class="form-control" name="area" value="" placeholder="Enter the Area">
            </div>
        </div>
    </div>


    <input type="hidden" class="form-control" name="body_id" value="{{ $body_id }}" >

    <div class="box-footer">
        {{--<div class="btn btn-info">Pull data from web</div>--}}
        <button type="submit" class="btn btn-primary pull-right">Save Changes</button>

    </div>
</div>